/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.*;
import model.Model;


/**
 *
 * @author pedro
 */
public class GUI extends javax.swing.JFrame {
     private Model m;

    public GUI() {
       
        initComponents();
        FileChooser.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        FileChooser = new javax.swing.JFileChooser();
        jPanel1 = new javax.swing.JPanel();
        btnObrirArxiu = new javax.swing.JButton();
        btnMostrarcaract = new javax.swing.JButton();
        btnCrearfitxer = new javax.swing.JButton();
        btnCreardirectori = new javax.swing.JButton();
        llegirbtn = new javax.swing.JCheckBox();
        escriurebtn = new javax.swing.JCheckBox();
        executarbtn = new javax.swing.JCheckBox();
        esfitxerbtn = new javax.swing.JRadioButton();
        esdirectoribtn = new javax.swing.JRadioButton();
        fitxercamp = new javax.swing.JTextField();
        PathJTF = new javax.swing.JTextField();
        obririmatgebtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        lblImagen = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaText = new javax.swing.JTextArea();
        btnGuardarImatge = new javax.swing.JButton();
        btnGuardarText = new javax.swing.JButton();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestió Arxius DAM");

        jPanel1.setBackground(new java.awt.Color(246, 199, 151));

        btnObrirArxiu.setText("Navegar");
        btnObrirArxiu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrirArxiuActionPerformed(evt);
            }
        });

        btnMostrarcaract.setText("Propietats");

        btnCrearfitxer.setText("Crea Fitxer");

        btnCreardirectori.setText("Crea Directori");

        llegirbtn.setText("Es pot llegir");
        llegirbtn.setEnabled(false);

        escriurebtn.setText("Es pot escriure");
        escriurebtn.setEnabled(false);

        executarbtn.setText("Es pot executar");
        executarbtn.setEnabled(false);

        esfitxerbtn.setText("És un fitxer");
        esfitxerbtn.setEnabled(false);

        esdirectoribtn.setText("És un directori");
        esdirectoribtn.setEnabled(false);

        fitxercamp.setText("Nom del fitxer o directori a crear");

        PathJTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PathJTFActionPerformed(evt);
            }
        });

        obririmatgebtn.setText("Obrir Arxiu");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(executarbtn)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(escriurebtn)
                            .addComponent(btnCrearfitxer))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(esfitxerbtn)
                            .addComponent(esdirectoribtn)
                            .addComponent(btnCreardirectori, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addComponent(fitxercamp, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(llegirbtn)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnObrirArxiu)
                        .addGap(18, 18, 18)
                        .addComponent(btnMostrarcaract, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(obririmatgebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(PathJTF, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 12, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnObrirArxiu)
                    .addComponent(btnMostrarcaract)
                    .addComponent(obririmatgebtn))
                .addGap(7, 7, 7)
                .addComponent(PathJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(llegirbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(esfitxerbtn, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(escriurebtn, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(executarbtn)
                    .addComponent(esdirectoribtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrearfitxer)
                    .addComponent(btnCreardirectori))
                .addGap(18, 18, 18)
                .addComponent(fitxercamp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84))
        );

        jScrollPane2.setViewportView(lblImagen);

        txtAreaText.setColumns(20);
        txtAreaText.setRows(5);
        jScrollPane1.setViewportView(txtAreaText);

        btnGuardarImatge.setText("Guardar Imatge");
        btnGuardarImatge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarImatgeActionPerformed(evt);
            }
        });

        btnGuardarText.setText("Guardar Text");
        btnGuardarText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarTextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnGuardarImatge)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardarText, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGuardarImatge))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGuardarText)))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnObrirArxiuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrirArxiuActionPerformed
       
    }//GEN-LAST:event_btnObrirArxiuActionPerformed

    private void btnGuardarImatgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarImatgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarImatgeActionPerformed

    private void btnGuardarTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarTextActionPerformed

    private void PathJTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PathJTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PathJTFActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser FileChooser;
    private javax.swing.JTextField PathJTF;
    private javax.swing.JButton btnCreardirectori;
    private javax.swing.JButton btnCrearfitxer;
    private javax.swing.JButton btnGuardarImatge;
    private javax.swing.JButton btnGuardarText;
    private javax.swing.JButton btnMostrarcaract;
    private javax.swing.JButton btnObrirArxiu;
    private javax.swing.JCheckBox escriurebtn;
    private javax.swing.JRadioButton esdirectoribtn;
    private javax.swing.JRadioButton esfitxerbtn;
    private javax.swing.JCheckBox executarbtn;
    private javax.swing.JTextField fitxercamp;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JCheckBox llegirbtn;
    private javax.swing.JButton obririmatgebtn;
    private javax.swing.JTextArea txtAreaText;
    // End of variables declaration//GEN-END:variables

    public Model getM() {
        return m;
    }

    public void setM(Model m) {
        this.m = m;
    }

    public JFileChooser getFileChooser() {
        return FileChooser;
    }

    public void setFileChooser(JFileChooser FileChooser) {
        this.FileChooser = FileChooser;
    }

    public JTextField getPathJTF() {
        return PathJTF;
    }

    public void setPathJTF(JTextField PathJTF) {
        this.PathJTF = PathJTF;
    }

    public JButton getBtnCreardirectori() {
        return btnCreardirectori;
    }

    public void setBtnCreardirectori(JButton btnCreardirectori) {
        this.btnCreardirectori = btnCreardirectori;
    }

    public JButton getBtnCrearfitxer() {
        return btnCrearfitxer;
    }

    public void setBtnCrearfitxer(JButton btnCrearfitxer) {
        this.btnCrearfitxer = btnCrearfitxer;
    }

    public JButton getBtnGuardarImatge() {
        return btnGuardarImatge;
    }

    public void setBtnGuardarImatge(JButton btnGuardarImatge) {
        this.btnGuardarImatge = btnGuardarImatge;
    }

    public JButton getBtnGuardarText() {
        return btnGuardarText;
    }

    public void setBtnGuardarText(JButton btnGuardarText) {
        this.btnGuardarText = btnGuardarText;
    }

    public JButton getBtnMostrarcaract() {
        return btnMostrarcaract;
    }

    public void setBtnMostrarcaract(JButton btnMostrarcaract) {
        this.btnMostrarcaract = btnMostrarcaract;
    }

    public JButton getBtnObrirArxiu() {
        return btnObrirArxiu;
    }

    public void setBtnObrirArxiu(JButton btnObrirArxiu) {
        this.btnObrirArxiu = btnObrirArxiu;
    }

    public JCheckBox getEscriurebtn() {
        return escriurebtn;
    }

    public void setEscriurebtn(JCheckBox escriurebtn) {
        this.escriurebtn = escriurebtn;
    }

    public JRadioButton getEsdirectoribtn() {
        return esdirectoribtn;
    }

    public void setEsdirectoribtn(JRadioButton esdirectoribtn) {
        this.esdirectoribtn = esdirectoribtn;
    }

    public JRadioButton getEsfitxerbtn() {
        return esfitxerbtn;
    }

    public void setEsfitxerbtn(JRadioButton esfitxerbtn) {
        this.esfitxerbtn = esfitxerbtn;
    }

    public JCheckBox getExecutarbtn() {
        return executarbtn;
    }

    public void setExecutarbtn(JCheckBox executarbtn) {
        this.executarbtn = executarbtn;
    }

    public JTextField getFitxercamp() {
        return fitxercamp;
    }

    public void setFitxercamp(JTextField fitxercamp) {
        this.fitxercamp = fitxercamp;
    }

    public JDialog getjDialog1() {
        return jDialog1;
    }

    public void setjDialog1(JDialog jDialog1) {
        this.jDialog1 = jDialog1;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JScrollPane getjScrollPane2() {
        return jScrollPane2;
    }

    public void setjScrollPane2(JScrollPane jScrollPane2) {
        this.jScrollPane2 = jScrollPane2;
    }

    public JLabel getLblImagen() {
        return lblImagen;
    }

    public void setLblImagen(JLabel lblImagen) {
        this.lblImagen = lblImagen;
    }

    public JCheckBox getLlegirbtn() {
        return llegirbtn;
    }

    public void setLlegirbtn(JCheckBox llegirbtn) {
        this.llegirbtn = llegirbtn;
    }

    public JTextArea getTxtAreaText() {
        return txtAreaText;
    }

    public void setTxtAreaText(JTextArea txtAreaText) {
        this.txtAreaText = txtAreaText;
    }

    public JButton getObririmatgebtn() {
        return obririmatgebtn;
    }

    public void setObririmatgebtn(JButton obririmatgebtn) {
        this.obririmatgebtn = obririmatgebtn;
    }

}


